site_name: 'Backstage Demo Python App'
site_description: 'Main documentation for Backstage Demo Python App'
repo_url: https://github.com/Thwani47/backstage-demo-python-app
edit_uri: edit/master/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting Started: 'docs/index.md'