name: ci

on:
  push:
    paths:
      - src/**
    branches:
      - master

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Shorten commit ID
        shell: bash
        run: |
         echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: 84733/backstage-demo-python-app:${{ env.COMMIT_ID }}